config/routes.rb
Opensit::Application.routes.draw do

  root :to => "pages#front"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  get 'me' => "users#me"

  constraints(:username => /[^\/]+/) do
    get '/u/:username' => "users#show", :as => :user
    get '/u/:username/following' => "users#following", :as => :following_user
    get '/u/:username/followers' => "users#followers", :as => :followers_user
    get '/u/:username/export' => "users#export"
    get '/u/:username/feed' => "users#feed", :as => :feed, :defaults => { :format => 'atom' }
  end

  get '/favs' => "favourites#index", :as => :favs
  get '/notifications' => "notifications#index"
  get '/welcome' => "users#welcome"
  get '/search' => "search#main"
  get 'about' => "pages#about"
  get 'contribute' => "pages#contribute"
  get 'contact' => "pages#contact"
  get 'explore' => "pages#explore"
  get 'explore/tags' => "pages#tag_cloud", :as => :explore_tags
  get 'explore/comments' => "pages#new_comments", :as => :explore_comments
  get 'explore/users/online' => "pages#online_users", as: :explore_online_users
  get 'explore/users/new' => "pages#new_users", :as => :explore_new_users
  get 'explore/users/active' => "pages#active_users", :as => :explore_active_users
  get 'explore/users/new/sitters' => "pages#new_sitters", :as => :explore_new_sitters
  get 'global-feed' => "users#feed", :defaults => { :format => 'atom', :scope => 'global' }
  get 'calendar' => "pages#calendar", :as => :calendar

  resources :sits do
    resources :comments
  end

  get '/tags/:id' => 'tags#show', :as => :tag
  get '/messages/sent' => "messages#sent", :as => :sent_messages
  resources :messages, except: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :reports, only: [:create]
  resources :goals

  # Crawl live site, but not staging
  get 'robots.txt' => 'pages#robots'

  get "/split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    request.env['warden'].user.email == "danbartlett@gmail.com"
  }
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def front
    @sits = Sit.newest_first.limit(5).all
    @newest_users = User.newest_users
  end

  def explore
  	@sits = Sit.newest_first.limit(5).all
  	@newest_users = User.newest_users
  end
  
  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	# Allow Devise forms in other controllers
	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<section class="about-page">

<h1>About</h1>

<p class="lead">OpenSit is a place where people who meditate can record their experiences and connect with each other.</p>

<p>We all share in the same highs and lows of the human condition, and more and more of us are choosing to meditate as means of cultivating peace and freedom, in this life.</p>

<p>A journal or practice log can be especially useful to reflect upon the journey of insight, and to inspire us to keep up with practice. OpenSit is an online practice log that allows you to record and share your practice, without having to cross reference blog posts, forum threads, emails and other scattered notes.</p>

<p>Your profile and stream are available all in one place, as a searchable chronological record of what you have done and what has happened as a result. This grounds our activity and discussion in the messy particulars of real people and real practice.</p>

<p>Building a website around the practice log keeps us focused on exactly that - practice. We’re not interested in who or what you believe, but what you <em>practice</em>. What happens when you sit down on the cushion, and how does this regular practice affect your sense of wellbeing, and the way you live within the world?</p>



<p>We can all benefit from recording our own insights, supporting each other’s practices, and sharing it all without fear of impinging upon taboo, tradition or dogma.</p>

<p>Anyone who has truly immersed themselves in contemplative practice knows that strange and wonderful things can and do happen on the cushion, and it’s time to talk about this honestly. The selflessness realised in authentic meditation is too important to stay under robes.</p>

<p>OpenSit is a contemplative expression platform 

<p>OpenSit is not a discussion forum – users can make short comments on each other’s sits and diaries but there is no open forum to create new threads. OpenSit is built around the practice log. As a result, activity and discussion is centred around the particulars of real people and real practice.</p>

<p>Welcome to OpenSit.</p>

<p class="lead">What's coming next?</p>

<p>Lots.</p>
<ul>
	<li>Teacher/student functionality</li>
</ul>

</section>

app/views/static_pages/front.html.erb
<div class="section front-page">
  
  <% if !user_signed_in? %>
    <section id="branding">
      
      <div class="hero-unit">
        
        <div class="left"><h1>Where meditators meet.</h1>
          <p>OpenSit is a place where people who meditate can record their experiences and connect with each other.</p>
        </div>
        
        <div class="right">
          <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>

            <div><%= f.text_field :username, placeholder: 'Pick a username' %></div>

            <div><%= f.email_field :email, placeholder: 'Enter your email' %></div>

            <div><%= f.password_field :password, placeholder: 'Choose a password' %></div>

            <!-- <div><%= f.password_field :password_confirmation, placeholder: 'Confirm password' %></div> -->

            <div><%= f.submit "Sign up", :class => 'pull-right btn btn-primary btn-large' %></div>
          <% end %>
        </div>
      </div>
      
      <div class="three-panes">
        <div class="pane">
          <i class="icon-book"></i>
          <h3>Start streaming today</h3>
          What do you practice and how has it changed you? Share your practice or start a private stream.</div>
        <div class="pane">
          <i class="icon-globe"></i>
          <h3>Connect with others</h3>
          Follow friends and discover new practitioners from different countries, cultures and traditions.</div>
        <div class="pane">
          <i class="icon-bolt"></i>
          <h3>Improve your practice</h3>
          Keeping a practice log encourages us. Support each other, be inspired by each other, and give your practice a boost.</div>
      </div>
      
    </section> <!-- end section#branding -->
  <% end %>
  
  <%#= render 'shared/explore' %>

</div> <!-- end div.front-page -->