config/routes.rb
Opensit::Application.routes.draw do

  root :to => "pages#front"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  get 'me' => "users#me"

  constraints(:username => /[^\/]+/) do
    get '/u/:username' => "users#show", :as => :user
    get '/u/:username/following' => "users#following", :as => :following_user
    get '/u/:username/followers' => "users#followers", :as => :followers_user
    get '/u/:username/export' => "users#export"
    get '/u/:username/feed' => "users#feed", :as => :feed, :defaults => { :format => 'atom' }
  end

  get '/favs' => "favourites#index", :as => :favs
  get '/notifications' => "notifications#index"
  get '/welcome' => "users#welcome"
  get '/search' => "search#main"
  get 'about' => "pages#about"
  get 'contribute' => "pages#contribute"
  get 'contact' => "pages#contact"
  get 'explore' => "pages#explore"
  get 'explore/tags' => "pages#tag_cloud", :as => :explore_tags
  get 'explore/comments' => "pages#new_comments", :as => :explore_comments
  get 'explore/users/online' => "pages#online_users", as: :explore_online_users
  get 'explore/users/new' => "pages#new_users", :as => :explore_new_users
  get 'explore/users/active' => "pages#active_users", :as => :explore_active_users
  get 'explore/users/new/sitters' => "pages#new_sitters", :as => :explore_new_sitters
  get 'global-feed' => "users#feed", :defaults => { :format => 'atom', :scope => 'global' }
  get 'calendar' => "pages#calendar", :as => :calendar

  resources :sits do
    resources :comments
  end

  get '/tags/:id' => 'tags#show', :as => :tag
  get '/messages/sent' => "messages#sent", :as => :sent_messages
  resources :messages, except: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :reports, only: [:create]
  resources :goals

  # Crawl live site, but not staging
  get 'robots.txt' => 'pages#robots'

  get "/split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    request.env['warden'].user.email == "danbartlett@gmail.com"
  }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from_user,  :class_name => 'User'
  belongs_to :to_user,    :class_name => 'User'

  attr_accessible :body, :subject, :from_user_id, :to_user_id, :read

  validates :body, :from_user_id, :to_user_id, :presence => true

  scope :unread, -> { where(read: false) }
  scope :newest_first, -> { order("created_at DESC") }

  ##
  # VIRTUAL ATTRIBUTES
  ##

  def received_at
    created_at.strftime("%l:%M%P, %d %B %Y")
  end

  ##
  # METHODS
  ##

  def mark_as_read
    self.read = true
    self.save
  end
end
# == Schema Information
#
# Table name: messages
#
#  body             :text
#  created_at       :datetime         not null
#  from_user_id     :integer
#  id               :integer          not null, primary key
#  read             :boolean          default(FALSE)
#  receiver_deleted :boolean          default(FALSE)
#  sender_deleted   :boolean          default(FALSE)
#  subject          :string(255)
#  to_user_id       :integer
#  updated_at       :datetime         not null
#

#

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :access_message?, :only => [:show, :destroy]

  # GET /messages
  # Inbox
  def index
    @user = current_user
    @messages = @user.messages_received.newest_first.limit(10)

    @title = 'Inbox'
    @page_class = 'inbox'
  end

  # GET /messages/1
  def show
    @user = current_user
    @message = Message.find(params[:id])
    @from_user = User.find(@message.from_user_id)
    @reply = Message.new(subject: "RE: " + @message.subject)

    # Only mark as read if the recipient is reading
    @message.mark_as_read unless @user.id == @from_user.id

    @title = "Message from #{@from_user.display_name}"
    @page_class = "view-message"
  end

  # GET /messages/new
  def new
    @user = current_user
    @message ||= Message.new

    @title = 'New message'
    @page_class = 'new-message'
  end

  # GET /messages/sent
  def sent
    @user = current_user
    @messages = @user.messages_sent.newest_first.limit(10)

    @title = 'Sent items'
    @page_class = 'sent-items'
  end

  # POST /messages
  def create
    @user = current_user

    @message = Message.new(params[:message])
    @message.to_user_id = params[:message][:to_user_id]
    @message.from_user_id = @user.id

    if !@message.valid?
      render action: "new"
    else
      @message.save!
      redirect_to messages_url, notice: 'Your message has been sent.'
    end
  end

  # DELETE /messages/1
  def destroy
    @user = current_user
    @message = Message.find(params[:id])

    if @user.id == @message.from_user_id
      @message.sender_deleted = true
    else
      @message.receiver_deleted = true
    end

    @message.save
    @message.destroy if @message.sender_deleted && @message.receiver_deleted

    redirect_to messages_url
  end

  # Is the current user allowed to view this message?
  def access_message?
    @user = current_user
    @message = Message.find(params[:id])

    return true if (@user.id == @message.from_user_id) or (@user.id == @message.to_user_id)
    redirect_to messages_path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def unread_marker(msg)
		if !msg.read
			'<i class="fa fa-asterisk"></i>'.html_safe
		end
	end

	def inbox_unread_count(user)
		user.unread_count if user.unread_count
	end
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message, :html => { :class => 'form-horizontal'}) do |f| %>
  <% if @message.errors.any? %>
    <div class="alert alert-danger">
      Please complete the required fields.
    </div>
  <% end %>

	<%= form_element(f, :to_user_id, 'message', "To", 4, { label: false, collection: User.all, label_method: 'username', input_html: { multiple: false, data: { placeholder: 'Choose a user'}, class: 'chzn-select' } }) %>

	<%= form_element(f, :subject, 'message', "Subject", 4, { label: false }) %>

	<%= form_element(f, :body, 'message', "Body", 9, { label: false, input_html: { class: 'rich-textarea', rows: 10 } }) %>

  <%= f.submit 'Send message', :class => 'btn btn-lg btn-primary' %>

<% end %>

app/views/messages/_message.html.erb
<a href="<%=messages_path%>" class="btn btn-default">&larr; Back to inbox</a>

<div class="title"><strong><%=@message.subject %></strong></div>
<div class="body"><%= @message.body.html_safe %></div>
<div class="message_details">
	<div class="from">
		<div class="avatar"><%= small_avatar_of(@message.from_user) %></div>
		<div class="username"><%= @message.from_user.display_name %></div>
	</div>
	<div class="date">Sent at <%= @message.received_at %></div>
	<div class="delete"><%= link_to 'Delete this message', message_path(@message), :method => :delete, :confirm => 'Are you sure?' %></div>
</div>
<div class="clearfix col-md-12">
  <%= render 'reply' %>
</div>

app/views/messages/_messages_tile.html.erb
<div class="header-tile tile stamp col-md-3">
	<div class="content">
		<h2>Messaging</h2>

	   <ul class="nav nav-pills nav-stacked">
	      <li <%='class=active' if current_page?(new_message_path) %>>
	        <a href="<%=new_message_path%>" class="item"><i class="pull-left fa fa-edit"></i> New message</a>
	      </li>
		  	<li <%='class=active' if current_page?(messages_path) %>>
				  <%= link_to(messages_path) do %>
				  	<i class="fa fa-envelope-o"></i> Inbox <span class="badge"><%= inbox_unread_count(@user) %></span>
				  <% end %>
				</li>
				<li <%='class=active' if current_page?(sent_messages_path) %>>
		  		<%= link_to(sent_messages_path) do %>
		  			<i class="fa fa-share"></i> Sent messages
		  		<% end %>
		 		</li>
		 </ul>
		</div>
</div>

app/views/messages/_reply.html.erb
<%= simple_form_for(@reply, :html => { :class => 'form-horizontal'}) do |f| %>
  <% if @reply.errors.any? %>
    <div class="alert alert-danger">
      Please complete the required fields.
    </div>
  <% end %>

  <%= f.input :to_user_id, :as => "hidden", :input_html => { :value => @from_user.id } %>

  <%= form_element(f, :subject, 'message', "Subject", 4, { label: false }) %>

  <%= form_element(f, :body, 'message', "", 9, { label: false, input_html: { class: 'rich-textarea', rows: 10 } }) %>

  <%= f.submit 'Reply', :class => 'btn btn-lg btn-primary' %>

<% end %>

app/views/messages/index.html.erb
<div class="sidebar col-md-3">
  <%= render 'messages_tile' %>
</div>

<div class="clearfix col-md-9">
  <% if @messages.empty? %>
    <div class="message-box">
      <h2>Your inbox is empty.</h2>
      <p>I'm sure someone is thinking of you...</p>
    </div>
  <% else %>

    <table class="table msg-overview">
      <% @messages.each do |msg| %>
        <% if User.where(id: msg.from_user_id).present? %>
          <tr>
            <td class="unread"><%= unread_marker(msg) %></td>
            <td class="msg-avatar"><%= small_avatar_of(msg.from_user) %></td>
            <td class="msg-content">
              <%= link_to 'X', message_path(msg), :method => :delete, :confirm => 'Delete this message?', :class => 'msg-delete' %>
              <a href="<%= message_path(msg) %>" class="clickable-row">
              <div class="msg-username"><%= msg.from_user.username %> says:</div>
              <div class="msg-content"><%= msg.subject.blank? ? truncate(msg.body, :length => 20, :omission => " ...").html_safe : msg.subject %></div>
              <div class="msg-received">Received <%= time_ago_in_words(msg.created_at) %> ago</div>
              </a>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>

  <% end %>
</div>

app/views/messages/new.html.erb
<div class="sidebar col-md-3">
  <%= render 'messages_tile' %>
</div>

<div class="clearfix col-md-9">
	<%= render 'form' %>
</div>

app/views/messages/sent.html.erb
<div class="sidebar col-md-3">
  <%= render 'messages_tile' %>
</div>

<div class="clearfix col-md-9">
  <% if @messages.empty? %>
    <div class="message-box">
      <h2>You haven't sent any messages.</h2>
      <p>Why don't you send someone a message?</p>
    </div>
  <% else %>

    <table class="table msg-overview">
      <% @messages.each do |msg| %>
        <% if User.where(id: msg.to_user_id).present? %>
          <tr>
            <td class="msg-avatar"><%= small_avatar_of(msg.to_user) %></td>
            <td class="msg-content">
              <%= link_to 'X', message_path(msg), :method => :delete, :confirm => 'Delete this message from your sent items?', :class => 'msg-delete' %>
              <a href="<%= message_path(msg) %>" class="clickable-row">
              <div class="msg-username">To: <%= msg.to_user.username %></div>
              <div class="msg-content"><%= msg.subject.blank? ? truncate(msg.body, :length => 20, :omission => " ...").html_safe : msg.subject %></div>
              <div class="msg-received">Sent <%= time_ago_in_words(msg.created_at) %> ago</div>
              </a>
            </td>
          </tr>
        <% end %>
      <% end %>
    </table>

  <% end %>
</div>

app/views/messages/show.html.erb
<div class="sidebar col-md-3">
  <%= render 'messages_tile' %>
</div>

<div class="clearfix col-md-9">
	<%= render 'message' %>
</div>