config/routes.rb
Opensit::Application.routes.draw do

  root :to => "pages#front"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  get 'me' => "users#me"

  constraints(:username => /[^\/]+/) do
    get '/u/:username' => "users#show", :as => :user
    get '/u/:username/following' => "users#following", :as => :following_user
    get '/u/:username/followers' => "users#followers", :as => :followers_user
    get '/u/:username/export' => "users#export"
    get '/u/:username/feed' => "users#feed", :as => :feed, :defaults => { :format => 'atom' }
  end

  get '/favs' => "favourites#index", :as => :favs
  get '/notifications' => "notifications#index"
  get '/welcome' => "users#welcome"
  get '/search' => "search#main"
  get 'about' => "pages#about"
  get 'contribute' => "pages#contribute"
  get 'contact' => "pages#contact"
  get 'explore' => "pages#explore"
  get 'explore/tags' => "pages#tag_cloud", :as => :explore_tags
  get 'explore/comments' => "pages#new_comments", :as => :explore_comments
  get 'explore/users/online' => "pages#online_users", as: :explore_online_users
  get 'explore/users/new' => "pages#new_users", :as => :explore_new_users
  get 'explore/users/active' => "pages#active_users", :as => :explore_active_users
  get 'explore/users/new/sitters' => "pages#new_sitters", :as => :explore_new_sitters
  get 'global-feed' => "users#feed", :defaults => { :format => 'atom', :scope => 'global' }
  get 'calendar' => "pages#calendar", :as => :calendar

  resources :sits do
    resources :comments
  end

  get '/tags/:id' => 'tags#show', :as => :tag
  get '/messages/sent' => "messages#sent", :as => :sent_messages
  resources :messages, except: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :reports, only: [:create]
  resources :goals

  # Crawl live site, but not staging
  get 'robots.txt' => 'pages#robots'

  get "/split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    request.env['warden'].user.email == "danbartlett@gmail.com"
  }
end

app/views/shared/_favourite-button.html.erb
<% unless (current_user and current_user.id == @sit.user_id) or !current_user %>
	<span id="favourite_button">
    <% if current_user and current_user.favourited?(@sit.id) %>
      <%= render 'favourites/unfavourite' %>
    <% else %>
      <%= render 'favourites/favourite' %>
    <% end %>
  </span>
<% end %>

app/views/shared/_follow-button.html.erb
<% unless (current_user == @user) || !current_user %>
	<div id="follow_form">
  	<% if current_user.following?(@user) %>
      <%= render 'users/unfollow' %>
    <% else %>
      <%= render 'users/follow' %>
    <% end %>
  </div>
<% end %>

app/views/shared/_follow_button.html.erb
<% unless (current_user == user) || !current_user %>
	<div class="follow_form" id="follow_form_<%=user.id%>">
  	<% if current_user.following?(user) %>
      <%= render 'users/unfollow', :user => user %>
    <% else %>
      <%= render 'users/follow', :user => user %>
    <% end %>
  </div>
<% end %>

app/views/shared/_full_user.html.erb
<%= large_avatar_of(@user) %>
<div class="sidebar-content">
	<div class="display_name" itemprop="name"><%= username(@user, false) %></div>
  <div class="username" itemprop="alternateName"><%= @user.username %></div>

  <%= render 'users/details' %>

	<%= render 'shared/follow_button', :user => @user %>
</div>

app/views/shared/_like_button.html.erb
<%# After AJAX load, form has no access to @sit so reload it %>
<% unless (current_user and current_user.id == @sit.user_id) or !current_user %>

	<div id="like_button" class="col-centered">
    <% if current_user and current_user.likes?(@sit) %>
			<%= form_for(@sit.likes.find_by_user_id(current_user.id), html: { method: :delete }, remote: true) do |f| %>
				<div><%= f.hidden_field :likeable_id, :value => @sit.id %></div>
			  <div><%= f.hidden_field :likeable_type, :value => 'Sit' %></div>
			  <a href="#" title="Unlike it" class="toggle-like"><span class="fa fa-heart"></span></a>
			<% end %>

    <% else %>
			<%= form_for(@sit.likes.build, remote: true) do |f| %>
			  <div><%= f.hidden_field :likeable_id, :value => @sit.id %></div>
			  <div><%= f.hidden_field :likeable_type, :value => 'Sit' %></div>
			  <a href="#" title="Like it!" class="toggle-like"><span class="fa fa-heart-o"></span></a>
			<% end %>
    <% end %>

  </div>

<% end %>

app/views/shared/_other-pills.html.erb
<%= link_to(feed_path(@user), :title => 'Subscribe to this users updates', :class => 'user-sit-feed') do %>
  <i class="icon-rss"></i>
<% end %>

<ul class="nav nav-tabs">
  <li <%='class=active' if params[:action] == "show" %>><%= link_to 'Sits', user_path %></li>
  <li <%='class=active' if params[:action] == "profile" %>><%= link_to 'Profile', profile_path(@user) %></li>
</ul>

app/views/shared/_recent-activity.html.erb
<div class="nav-module recent-activity">
	<% if @my_latest.empty? %>
		<div class="add-a-sit"><%= link_to '<i class="icon-plus"></i> Add your first sit'.html_safe, new_sit_path %></div>
	<% else %>
		<% if current_user.id == @user.id %>
			<h4>My Recent Activity</h4>
		<% else %>
			<h4><%= @user.display_name %>'s Activity</h4>
		<% end %>
		<% @my_latest.each do |sit| %>
			<article class="sit-teaser">
				<div class="title">
					<% if sit.s_type == 0 %>
						<i class="icon-user"></i>
					<% else %>
						<i class="icon-book"></i>
					<% end %>
					<%= teaser_title(sit, 'latest') %>
				</div>
				<div class="body">
					<%= teaser(sit, 100) %>
				</div>
				<div class="date muted">
					<%= time_ago_in_words(sit.created_at) %> ago
				</div>
			</article>
		<% end %>
	<% end %>
</div>

app/views/shared/_sidebar-user.html.erb
<div class="avatar-container"><%= avatar(@user, 1) %></div>
<div class="sidebar-content">
	<div class="username"><%= username(@user) %></div>
	<% if !@user.city.blank? || !@user.country.blank? %>
		<div class="user-info">
			<div class="icon"><i class="icon-flag"></i></div><div class="detail"><%= @user.location %></div>
		</div>
	<% end %>
	<% if !@user.style.blank? %>
		<div class="user-info">
			<div class="icon"><i class="icon-bolt"></i></div><div class="detail"> <%= @user.style %></div>
		</div>
	<% end %>
	<% if !@user.website.blank? %>
		<div class="user-info">
			<div class="icon"><i class="icon-link"></i></div><div class="detail"> <%= website(@user) %></div>
		</div>
	<% end %>

	<div class="user-info">
		<div class="icon"><i class="icon-user"></i></div><div class="detail"><%= link_to 'View profile', profile_path(@user) %></div>
	</div>

	<%= render 'shared/stats' %>

	<%= render 'shared/follow-button' %>
</div>

app/views/shared/_sidebar-users.html.erb
<% if controller.action_name.in? ['my_sits'] %>
	<%= render 'shared/user-summary' %>
	
	<% if !@user.sits.empty? %>
		<div class="nav-module my-timeline">
			<ul>
			<%= timeline(@links) %>
			</ul>
		</div>
	<% end %>

<% elsif controller.action_name.in? ['profile', 'show'] %>
	<%= render 'shared/full-user' %>
	
<% else %>
	<%= render 'shared/user-summary' %>
	<%= render 'shared/recent-activity' %>
<% end %>

app/views/shared/_sit-teaser.html.erb
<article class="sit-teaser">
  <div class="side">
    <%= small_avatar_of(sit.user) %>
  </div>

  <div class="sit-content">

    <div class="top"><%= username(sit.user) %> <%= teaser_title(sit) %>
    <% if sit.comments.count > 0 %>
      &bull; <%= pluralize(sit.comments.count, 'comment') %>
    <% end %>
      <span class="pull-right">
      <% if request.fullpath =~ /my/ %>
        <%= sit.date %>
      <% else %>
       <%= time_ago_in_words(sit.created_at) %> ago
      <% end %>
      </span></div>

    <div class="body"><%= teaser(sit) %></div>

  </div> <!-- end .sit-content -->

</article>

app/views/shared/_sit_teaser_block.html.erb
<article class="sit-teaser-block tile <%= "col-md-#{width}" %>">

<div class="block-content">

  <% if !sit.body.empty? %>
    <div class="body">
      <% if request.path =~ /search/ %>
        <%= teaser(sit, 300, params[:q]) %>
      <% else %>
        <%= teaser(sit) %>
      <% end %>
    </div>
    <%= display_lock_if_private(sit) %>
  <% end %>

  <div class="bottom-row">
    <div class="avatar">
      <%= small_avatar_of(sit.user) %>
    </div>
    <div class="details">
      <div class="author-title"><%= username(sit.user) %> <%= teaser_title(sit) %></div>
      <div class="meta">
        <span class="date">
          <% if params[:year] %>
            <%= sit.date %>
          <% else %>
            <%= time_ago_in_words(sit.created_at) %> ago
          <% end %>
        </span>
        <% if sit.liked? %>
          <i class="fa fa-heart"></i> <%= sit.likes.count %>
        <% end %>
        <% if sit.comments.count > 0 %>
          <i class="fa fa-comment"></i> <%= sit.comments.count %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</article>

app/views/shared/_suggested_users_block.html.erb
<div class="suggested-users">
  <h2>Who To Follow</h2>
  <%= render partial: 'shared/suggested_user', collection: users %>
</div>

app/views/shared/_user-summary.html.erb
<div class="nav-module user-summary">
	<div class="top-row">
		<div class="my-avatar"><%= small_avatar_of(@user) %></div>
		<div class="my-basics"><span class="username"><%= username(@user) %></span>
			<% if !@user.city.blank? || !@user.country.blank? %>
				<div class="my-location"><%= @user.location %></div>
			<% end %>
		</div>
	</div>

	<%= render 'shared/stats' %>
	<%= render 'shared/follow-button' %>
</div>

app/views/shared/_user.html.erb
<div class="user-teaser">
  <div class="avatar"><%= small_avatar_of(u) %></div>
  <div class="details">
	  <div class="name"><%= link_to(user_path(u)) do %>
		  <%= u.username %>
		  <% if !u.first_name.blank? %>
		  	(<%= u.display_name %>)
		  <% end %>
		 <% end %>
	  </div>
	  <% if u.sits_count.nonzero? %>
	  	<div class="sit-count">&mdash; <%= pluralize(u.sits.count, 'sit') %></div>
	  <% end %>
	  <div class="location">
	  <%= "#{u.location}." if u.location %>
	  <span class="joined">Joined <%= joined_date(u) %></span></div>
	  <%= render :partial => "shared/follow_button", :locals => { :user => u } %>
	 </div>
	 <div>

	 </div>
</div>