config/routes.rb
Opensit::Application.routes.draw do

  root :to => "pages#front"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  get 'me' => "users#me"

  constraints(:username => /[^\/]+/) do
    get '/u/:username' => "users#show", :as => :user
    get '/u/:username/following' => "users#following", :as => :following_user
    get '/u/:username/followers' => "users#followers", :as => :followers_user
    get '/u/:username/export' => "users#export"
    get '/u/:username/feed' => "users#feed", :as => :feed, :defaults => { :format => 'atom' }
  end

  get '/favs' => "favourites#index", :as => :favs
  get '/notifications' => "notifications#index"
  get '/welcome' => "users#welcome"
  get '/search' => "search#main"
  get 'about' => "pages#about"
  get 'contribute' => "pages#contribute"
  get 'contact' => "pages#contact"
  get 'explore' => "pages#explore"
  get 'explore/tags' => "pages#tag_cloud", :as => :explore_tags
  get 'explore/comments' => "pages#new_comments", :as => :explore_comments
  get 'explore/users/online' => "pages#online_users", as: :explore_online_users
  get 'explore/users/new' => "pages#new_users", :as => :explore_new_users
  get 'explore/users/active' => "pages#active_users", :as => :explore_active_users
  get 'explore/users/new/sitters' => "pages#new_sitters", :as => :explore_new_sitters
  get 'global-feed' => "users#feed", :defaults => { :format => 'atom', :scope => 'global' }
  get 'calendar' => "pages#calendar", :as => :calendar

  resources :sits do
    resources :comments
  end

  get '/tags/:id' => 'tags#show', :as => :tag
  get '/messages/sent' => "messages#sent", :as => :sent_messages
  resources :messages, except: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :favourites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :reports, only: [:create]
  resources :goals

  # Crawl live site, but not staging
  get 'robots.txt' => 'pages#robots'

  get "/split" => Split::Dashboard, :anchor => false, :constraints => lambda { |request|
    request.env['warden'].authenticated?
    request.env['warden'].authenticate!
    request.env['warden'].user.email == "danbartlett@gmail.com"
  }
end

app/models/sit.rb
require 'textacular/searchable'

class Sit < ActiveRecord::Base
  attr_accessible :private, :disable_comments, :tag_list, :duration, :s_type,
                  :body, :title, :created_at, :user_id, :views, :drawing

  belongs_to :user, counter_cache: true
  has_many :comments, :dependent => :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :favourites, :as => :favourable
  has_many :likes, :as => :likeable
  has_many :reports, :as => :reportable
  has_attached_file :drawing, styles: { large: "1024", medium: "800", small: "300" }

  validates :s_type, :presence => true
  validates :title, :presence => true, :if => "s_type != 0"
  validates :duration, :presence => true, :if => "s_type == 0"
  validates_numericality_of :duration, greater_than: 0, only_integer: true
  validates_attachment_content_type :drawing, content_type: /\Aimage\/.*\Z/

  # Scopes
  scope :communal, -> { where(private: false) }
  scope :newest_first, -> { order("created_at DESC") }
  scope :today, -> { where("DATE(created_at) = ?", Date.today) }
  scope :yesterday, -> { where("DATE(created_at) = ?", Date.yesterday) }
  scope :with_body, -> { where.not(body: '')}

  # Pagination: sits per page
  self.per_page = 20

  # Textacular: search these columns only
  extend Searchable(:title, :body)

  ##
  # VIRTUAL ATTRIBUTES
  ##

  # Nice date: 11 July 2012
  def date
    created_at.strftime("%d %B %Y")
  end

  # For use on show sit pages
  def full_title
    if s_type == 0
      "#{self.duration} minute meditation journal"
    elsif s_type == 1
      self.title # Diary
    else
      "Article: #{self.title}" # Article
    end
  end

  ##
  # METHODS
  ##

  def is_sit?
    s_type == 0
  end

  def stub?
    body.empty?
  end

  # Remove <br>'s and &nbsp's
  def custom_strip
    no_brs = self.body.gsub(/<br>/, ' ')
    no_brs.gsub('&nbsp;', ' ')
  end

  def mine?(current)
    return true if self.user_id == current.id
  end

  def next(current_user)
    next_sit = user.sits.with_body.where("created_at > ?", self.created_at).order('created_at ASC')
    return next_sit.first if current_user && (self.user_id == current_user.id)
    return next_sit.communal.first
  end

  def prev(current_user)
    prev_sit = user.sits.with_body.where("created_at < ?", self.created_at).order('created_at ASC')
    return prev_sit.last if current_user && (self.user_id == current_user.id)
    return prev_sit.communal.last
  end

  # Returns sits from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"

    where("(user_id IN (#{followed_user_ids}) AND private = false) OR user_id = :user_id",
          user_id: user.id)
  end

  def commenters
    ids = self.comments.map {|c| c.user.id}.uniq # uniq removes dupe ids if someone's posted multiple times
    ids.delete(self.user.id) # remove owners id
    return ids
  end

  ##
  # TAGS
  ##

  def self.tagged_with(name)
    Tag.find_by_name!(name).sits.communal
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").
      joins(:taggings).group("taggings.tag_id, tags.id, tags.name, tags.created_at")
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    elements = names.split(",")
    elements.reject! { |c| c.blank? } # Prevent blank tags being added
    self.tags = elements.map do |t|
      Tag.where(name: t.strip).first_or_create!
    end
  end

  ##
  # LIKES
  ##

  def likers
    Like.likers_for(self)
  end

  def liked?
    !self.likes.empty?
  end

end

# == Schema Information
#
# Table name: sits
#
#  body             :text
#  created_at       :datetime         not null
#  disable_comments :boolean
#  duration         :integer
#  id               :integer          not null, primary key
#  private          :boolean          default(FALSE)
#  s_type           :integer
#  title            :string(255)
#  updated_at       :datetime         not null
#  user_id          :integer
#  views            :integer          default(0)
#

app/controllers/sits_controller.rb
class SitsController < ApplicationController
  before_filter :authenticate_user!

  # GET /sits/1
  def show
    @sit = Sit.find(params[:id])
    @latest = @sit.user.latest_sit(current_user)

    # For completely private sits
    if @sit.private == true
      redirect_to me_path if current_user.nil? || (@sit.user_id != current_user.id)
    end

    # Views, not very accurate as any guest visit increments by one
    if current_user
      @sit.increment!(:views, by = 1) if current_user.id != @sit.user_id
    else
      @sit.increment!(:views, by = 1)
    end

    @user = @sit.user

    if @sit.is_sit?
      @title = "#{@sit.duration} minute meditation journal by #{@user.display_name}"
    else
      @title = "#{@sit.title}, a meditation journal by #{@user.display_name}"
    end

    @previous = @sit.prev(current_user)
    @next = @sit.next(current_user)

    @page_class = 'view-sit'
  end

  # GET /sits/new
  def new
    @sit ||= Sit.new
    @user = current_user

    @title = 'New sit'
    @page_class = 'new-sit'
  end

  # GET /sits/1/edit
  def edit
    @sit = Sit.find(params[:id])

    if current_user == @sit.user
      @user = current_user

      @title = 'Edit sit'
      @page_class = 'edit-sit'
    else
      redirect_to root_path, notice: "You can't edit this post"
    end
  end

  # POST /sits
  def create
    @user = current_user
    @sit = @user.sits.new(params[:sit])

    @sit.private = true if @user.private_stream
    @sit.created_at = DateTime.strptime(params[:custom_date], "%m/%d/%Y %l:%M %p") if params[:custom_date] != ''

    if @sit.save
      if !@sit.body.empty?
        redirect_to @sit, notice: 'Your entry was added. Good job!'
      else
        redirect_to user_path(@user, year: Date.today.year, month: Date.today.month), notice: 'Your entry was added. Good job!'
      end
    else
      @page_class = 'new-sit'
      render action: "new"
    end
  end

  # PUT /sits/1
  def update
    @sit = Sit.find(params[:id])

    if current_user == @sit.user
      @sit.created_at = DateTime.strptime(params[:custom_date], "%m/%d/%Y %l:%M %p") if params[:custom_date]

      if @sit.update_attributes(params[:sit])
        redirect_to @sit, notice: 'Sit was successfully updated.'
      else
        render action: "edit"
      end
    else
      redirect_to root_path, notice: "You can't edit this post"
    end
  end

  # DELETE /sits/1
  def destroy
    @sit = Sit.find(params[:id])

    if current_user == @sit.user
      @sit.destroy
      redirect_to me_path
    else
      redirect_to root_path, notice: "You can't delete this post"
    end
  end
end

app/helpers/sits_helper.rb
module SitsHelper
	def teaser(sit, length = 300, search = nil)
		stripped = strip_tags(sit.custom_strip)
		if search
			excerpt = excerpt(stripped, search, radius: 200)
			if !excerpt.blank?
				return highlight(excerpt, search)
			else
				return truncate(stripped, :length => length, :omission => " ...")
			end
		end
		return truncate(stripped, :length => length, :omission => " ...")
	end

	def teaser_title(sit, type = false)
		if sit.s_type == 0
      title = " sat for <a class='sit-link' title='#{sit.duration} minute meditation report by #{sit.user.display_name}' href='#{sit_path(sit)}'>#{sit.duration} minutes</a>".html_safe
		elsif sit.s_type == 1
			title = "added a <a class='sit-link' title='#{sit.title} by #{sit.user.display_name}' href='#{sit_path(sit)}'>diary</a>.".html_safe
		end
		return title
	end

	def display_lock_if_private(sit)
		if sit.private
			'<div class="private-event pull-right" title="This is a private entry. Only you can see it."><i class="fa fa-lock"></i></div>'.html_safe
		end
	end
end

app/views/sits/_back_button.html.erb
<% if request.referrer =~ /search/ %>
  <a href="<%=request.referrer%>" class="back-button btn btn-default">&larr; Back to search results</a>
<% elsif request.referrer =~ /explore/ %>
  <a href="<%=request.referrer%>" class="back-button btn btn-default">&larr; Back to explore</a>
<% elsif request.referrer =~ /tags/ %>
  <a href="<%=request.referrer%>" class="back-button btn btn-default">&larr; Back to tag</a>
<% elsif request.referrer =~ /favs/ %>
  <a href="<%=request.referrer%>" class="back-button btn btn-default">&larr; Back to favourites</a>
<% elsif request.referrer =~ /u/ %>
  <a href="<%=request.referrer%>" class="back-button btn btn-default">&larr; Back to timeline</a>
<% end %>

app/views/sits/_day_journal.html.erb
<% if @listed.last != sit.created_at.to_date %>
  <hr>
  <div class="day-of-the-month"><div class="weekday"><%=sit.created_at.strftime("%a")%></div><div class="date"><%=sit.created_at.strftime("%d")%></div></div>
<% end %>

<% @listed.push(sit.created_at.to_date) %>

<div class="entry">
  <% if sit.is_sit? %>
  	<% if sit.stub? %>
    	<div class="link"><i class='fa fa-clock-o'></i> <%=sit.duration%></div>
    <% else %>
    	<div class="link"><%= link_to "<i class='fa fa-clock-o'></i> #{sit.duration}".html_safe, sit_path(sit) %></div>
    <% end %>
    <div class="teaser"><%= sit.body.empty? ? '&nbsp;'.html_safe : teaser(sit, 150)%></div> <br>
  <% else %>
    <div class="link"><%= link_to "<i class='fa fa-book'></i>".html_safe, sit_path(sit) %></div>
    <div class="teaser"><em><%= sit.title %></em>: <%= teaser(sit, 140)%></div> <br>
  <% end %>
</div>

app/views/sits/_form.html.erb
<%= simple_form_for(@sit, :html => { :class => 'form-horizontal', multipart: true}) do |f| %>
  <% if @sit.errors.any? %>
    <div class="alert alert-danger">
      Please fill in the required fields.
    </div>
  <% end %>

  <%= if controller.action_name == 'edit'
    link_to 'Delete', sit_path(@sit), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger delete-entry pull-right'
    end %>

  <% if !current_user.private_stream %>
    <div class="dropdown privacy-options">
      <button data-toggle="dropdown" href="#" type="button" class="btn btn-small privacy-button"><i class="fa fa-cog"></i> Privacy</button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li>
          <div class="checkbox boolean optional sit_private">
            <input name="sit[private]" type="hidden" value="0" />
            <label class="checkbox">
              <input class="boolean optional" id="sit_private" name="sit[private]" type="checkbox" <%= @sit.private ? 'checked' : '' %> value="1" />
              Make this entry private
            </label>
          </div>
        </li>
        <li>
          <div class="checkbox boolean optional sit_disable_comments">
            <input name="sit[disable_comments]" type="hidden" value="0" />
            <label class="checkbox" for="sit_disable_comments">
              <input class="boolean optional" id="sit_disable_comments" name="sit[disable_comments]" type="checkbox" <%= @sit.disable_comments ? 'checked' : '' %> value="1" />
              Disable comments
            </label>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
  <div class="pull-right">
    <span class="label label-primary"><i class="fa fa-lock"></i> Your stream is private.</span>
  </div>
  <% end %>


  <div class="row">
    <div class="col-lg-offset-2 col-sm-8 sit_type">
      <div class="radio">
        <label>
          <input <%= @sit.s_type == 0 || @sit.s_type.nil? ? 'checked' : '' %> id="sit_s_type_0" name="sit[s_type]" type="radio" value="0" />
          I just sat for <input class="optional form-control" id="sit_duration" name="sit[duration]" size="50" type="text" value="<%= controller.action_name == 'edit' ? @sit.duration : @user.default_sit_length %>"> minutes
        </label>
      </div>

      <div class="radio">
        <label>
          <input <%= @sit.s_type == 1 ? 'checked' : '' %> class="diary_type" id="sit_s_type_1" name="sit[s_type]" type="radio" value="1" />This is a diary entry.
        </label>
      </div>
    </div>
  </div>

  <div class="new-sit-title">
    <%= form_element(f, :title, 'sit', "Title", 4, { label: false }) %>
  </div>

  <%= form_element(f, :body, 'sit', "What happened?", 7, { label: false, hint: 'You don\'t have to write anything', input_html: { rows: 10, autofocus: true, class: "rich-textarea" }} ) %>


  <%= form_element(f, :drawing, 'sit', "Drawing", 7, { label: false }) %>

  <div class='form-group'>
    <label class='col-lg-2 control-label' for='sit_created_at'>Date</label>
    <div class="col-lg-2">
      <div class="form-group string optional sit_created_at">
        <div class="col-lg-12">
          <div class="custom-date">
            <div class='input-group date' id='datetimepicker'>
                <input type='text' placeholder="Just now" name="custom_date" class="form-control" value="<%= controller.action_name == 'edit' ? @sit.created_at.strftime('%m/%d/%Y %l:%M %p') : '' %>" />
                <span class="input-group-addon"><span class="fa fa-calendar"></span>
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= form_element(f, :tag_list, 'sit', "Tags", 2, { hint: 'Separate by commas', label: false }) %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => 'btn btn-lg btn-primary' %>
    </div>
  </div>

<% end %>

app/views/sits/_sit-meta.html.erb
<div class="nav-module sit-meta">
	<div class="date"><%= @sit.date %></div>
  <ul class="pager">
	  <%= previous_sit(@sit) %>
	  <%= next_sit(@sit) %>
	</ul>
  
  <% if !@sit.tags.empty? %>
		<div class="sit-tags">
		  <div class="tags">
		    <i class="icon-tag"></i><%= tag_labels(@sit.tags) %>
		  </div>
		</div>
	<% end %>
 
  <%= render :partial => 'shared/favourite-button' %>
</div>

app/views/sits/_sit_preview.html.erb
<div class="content">
  <div><%= teaser(sit, 140).html_safe %></div>
</div>

app/views/sits/edit.html.erb
<%= render 'form' %>

app/views/sits/new.html.erb
<%= render 'form' %>

app/views/sits/show.html.erb
<div class="sidebar col-md-3">
  <%= render 'shared/user_summary' %>
</div>

<div class="clearfix col-md-9">
  <div class="text-section">

    <%= render 'back_button' %>

    <header>
      <div class="mobile-user-summary">
        <%= small_avatar_of(@user) %>
        <%= username(@user) %>
      </div>

      <h1 class="sit-title"><%= @sit.full_title %></h1>

      <div class="sit-stats">
        <div class="stat">
          <% if current_user and @sit.mine?(current_user) %>
            <%= link_to 'Edit', edit_sit_path(@sit) %>
          <% end %>
        </div>
        <div class="stat">
          <i class="fa fa-clock-o"></i> <span title=""><%= @sit.date %> <%= @sit.created_at.strftime("%l:%M %p") %></span>
        </div>
        <div class="stat">
          <%= "<i class='fa fa-heart'></i> #{@sit.likes.count}".html_safe if @sit.liked? %>
        </div>
        <div class="stat">
          <%= "<i class='fa fa-comment'></i> #{@sit.comments.count}".html_safe if @sit.comments.present? %>
        </div>
      </div>

      <div class="tags-container">
        <% if !@sit.tags.empty? %>
          <span class="fa fa-tags"></span><%= tag_labels(@sit.tags) %>
        <% end %>
      </div>
    </header>

    <% if @sit.user.private_stream %>
      <div class="private-warning">
        <span class="label label-primary"><i class="fa fa-lock"></i> Your stream is private.</span>
      </div>
    <% elsif @sit.private %>
      <div class="private-warning">
        <span class="label label-primary"><i class="fa fa-lock"></i> This is a private entry.</span>
      </div>
    <% end %>

    <div class="body">
      <%= @sit.body.html_safe %>
    </div>

    <% if @sit.drawing? %>
    <div class="drawing">
      <%= image_tag @sit.drawing.url(:medium) %>
    </div>
    <% end %>


    <% if current_user %>
      <div class="row">
        <div class="like-row<%= ' my-sit' if current_user == @user %>">
          <div class="col-md-12 like-it">
            <div id="who_likes">
              <%= render 'likes/like_module' %>
            </div>
            <%= render 'shared/like_button' %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <i class="fa fa-flag-o report-flag" data-container='body' data-toggle='tooltip' data-placement='top' title='Report something on this page'></i>
          <%= render 'reports/report_modal', reportable: @sit %>
        </div>
      </div>
    <% end %>

      <div class="prev-next-row">
        <% if @previous %>
          <div class="sit_preview previous">
            <%= link_to sit_path(@previous) do %>
              <div class="arrow">
                <i class="fa fa-chevron-left"></i>
              </div>
              <%= render partial: 'sit_preview', locals: { sit: @previous } %>
            </div>
          <% end %>
        <% end %>

        <% if @next %>
          <div class="sit_preview next">
            <%= link_to sit_path(@next) do %>
              <%= render partial: 'sit_preview', locals: { sit: @next } %>
              <div class="arrow">
                <i class="fa fa-chevron-right"></i>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

  <% if !@sit.disable_comments && !@sit.private %>
    <div class="comments">
      <% if !@sit.comments.empty? %>
        <h2>Comments</h2>
      <% end %>
      <div class="comments-list">
        <% @sit.comments.order(:created_at).each do |comment|
          @comment = comment %>
          <%= render 'comments/comment' %>
        <% end %>
      </div>

      <% if user_signed_in? %>
      <div class="new-comment">
        <%= simple_form_for [@sit, @sit.comments.build], :remote => 'true' do |f| %>
          <%= f.input :body, :label => false, :input_html => { :rows => 8, :class => 'rich-textarea col-md-12', :placeholder => 'Have your say.' } %>
          <%= f.submit 'Post comment', :class => 'post-comment-btn btn btn-primary btn-lg pull-right' %>
        <% end %>
      </div>
      <% end %>

    <% end %>
  </div>
</div>